[palettes.custom]
black = '#303338'
red = '#EF7178'
green = '#91A995'
yellow = '#E7C366'
blue = '#28B6F6'
purple = '#EE5896'
cyan = '#A5DDF2'
white = '#F0EEE6'

bright-black = '#929AA6'
bright-red = '#F49FA4'
bright-green = '#AEBFB1'
bright-yellow = '#EED492'
bright-blue = '#59C7F8'
bright-purple = '#F386B3'
bright-cyan = '#D2EEF8'
bright-white = '#FAF9F6'

accent = '#EE5896'
accent-secondary = '#28B6F6'
on-accent = '#17191D'
surface = '#212328'
border = '#393D43'
muted = '#929AA6'
info = '#28B6F6'
hint = '#929AA6'
success = '#91A995'
warning = '#E7C366'
error = '#EF7178'
