#!/usr/bin/env lua

-- Set up config path
local config_home = os.getenv("XDG_CONFIG_HOME") or (os.getenv("HOME") .. "/.config")
local config_path = config_home .. "/sketchybar"

-- Add config directory to Lua path
package.path = config_path .. "/?.lua;" .. config_path .. "/?/init.lua;" .. package.path

-- Add SbarLua to cpath
package.cpath = package.cpath .. ";" .. os.getenv("HOME") .. "/.local/share/sketchybar_lua/?.so"

-- Load and run
require("init")
